name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v4
      - name: Run Tests
        run: |
          fluentci run . test
          cd demo
          ../envhub init
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          ../envhub use
          type hello
          hello
          ../envhub unuse
        env:
          CLOUDFLARE_ROOT_KEY: 123
