on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            extensions: tar.gz tar.gz.sha256
          - target: aarch64-apple-darwin
            extensions: tar.gz tar.gz.sha256

    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.37
      - name: Setup Fluent CI CLI
        run: deno install -A -r https://cli.fluentci.io -n fluentci
      - name: Setup Dagger
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.8.8 sh
          sudo mv bin/dagger /usr/local/bin
          dagger version
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: stable
          args: -p envhub --release --target ${{ matrix.target }}
      - name: Install aarch64-apple-darwin toolchain
        if: matrix.target == 'aarch64-apple-darwin'
        run: rustup target add aarch64-apple-darwin
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf envhub_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz envhub
          shasum -a 256 envhub_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz > envhub_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha256
      - name: Upload release assets
        run: fluentci run github_pipeline release_upload
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          FILE: target/${{ matrix.target }}/release/envhub_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.${{ matrix.extensions }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
